{% set name = "snoop" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snoop-{{ version }}.tar.gz
  sha256: c615eddf84d8907f893dec7fde38768aa4b1d88d92d63055b6cfc07e5cde37ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens
    - cheap_repr >=0.4.0
    - executing
    - pygments
    - python >=3.6
    - six

test:
  imports:
    - snoop
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/alexmojaki/snoop
  summary: Powerful debugging tools for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
