{% set name = "snoop" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snoop-{{ version }}.tar.gz
  sha256: 2e0930bb19ff0dbdaa6f5933f88e89ed5984210ea9f9de0e1d8231fa5c1c1f25

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens
    - cheap_repr >=0.4.0
    - executing
    - pygments
    - python >=3.6
    - six

test:
  imports:
    - snoop
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/alexmojaki/snoop
  summary: Powerful debugging tools for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
